# -*- coding: utf-8 -*-
"""Input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXu_0hgNFe5AoWSS-qQR9CXOyOO7OxKx
"""

################## Input script file for module qr_factorization.py     ################################################# 


import qr_factorization as qrf  # Importing the QR module
import numpy as np # Import Numpy library as np
A = np.array([[1,2,0,0,0],[2,1,2,0,0],[0,2,1,2,0],[0,0,2,1,2],[0,0,0,2,1]])  # Given Problem Matrix
n = len(A)      # Give the order of the square matrix
Tolerance = 0.9898 # Tolerance argument to achieve convergence
max_iter = 8000         # Max number of allowed itreation upto user wants to iterate                                                   
int_iter = True # "True" for printing intermidiate iterations and "False" for not printing  

qrf.QR(A, n, max_iter, int_iter, Tolerance)  # Calling the function