# -*- coding: utf-8 -*-
"""input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TefXPBzd2DvugO_tGi7bLOIE4tQm2-Ft
"""

import numpy as np
from quadratic_fitting import *
X = np.linspace(50,825,32)
T_1=np.linspace(50,825,200)
y = np.array([62, 74.7, 79.7, 82, 93.4, 94, 105, 113.82, 139, 135,
  138, 130, 148, 160, 161, 170, 175.25, 182.05, 195, 198, 199, 209.37,
  220, 227, 229.9, 239, 243.5, 240.33, 243, 269, 270.8, 285])
skip=2
R_value1=51
R_value2=192.8
quadratic_fit(X,y,skip,T_1, R_value1, R_value2)